name: Quality checks
on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]
jobs:
  quality:
    name: Run checks for pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
      - id: modules-cache
        uses: actions/cache@v3.0.4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.modules-cache.outputs.cache-hit != 'true'
      - run: yarn format:ci
      - run: yarn lint:ci
      - run: yarn typecheck
      - run: yarn test:ci